# LOAD DATASET

In [10]:
import pandas as pd
import numpy as np


concrete_data = pd.read_csv('concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

# PREPROCESSING

In [11]:
concrete_data.shape
concrete_data.describe()
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [12]:

concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [13]:

target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [ ]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

In [14]:
 
n_cols = predictors.shape[1] # number of predictors
n_cols

8

# MODEL BUILDING

In [15]:

import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=42)

# build the model
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error')

# TRAINING

In [16]:
epochs = 50
model.fit(X_train, y_train, epochs=epochs, verbose=1)

Epoch 1/50
23/23 [==============================] - 1s 3ms/step - loss: 192907.0781
Epoch 2/50
23/23 [==============================] - 0s 3ms/step - loss: 79739.8281
Epoch 3/50
23/23 [==============================] - 0s 2ms/step - loss: 24548.3281
Epoch 4/50
23/23 [==============================] - 0s 2ms/step - loss: 5557.7671
Epoch 5/50
23/23 [==============================] - 0s 2ms/step - loss: 1625.6444
Epoch 6/50
23/23 [==============================] - 0s 2ms/step - loss: 1244.1536
Epoch 7/50
23/23 [==============================] - 0s 1ms/step - loss: 1203.7985
Epoch 8/50
23/23 [==============================] - 0s 1ms/step - loss: 1164.0751
Epoch 9/50
23/23 [==============================] - 0s 4ms/step - loss: 1122.9481
Epoch 10/50
23/23 [==============================] - 0s 2ms/step - loss: 1081.7089
Epoch 11/50
23/23 [==============================] - 0s 2ms/step - loss: 1039.0319
Epoch 12/50
23/23 [==============================] - 0s 3ms/step - loss: 999.2690
Epoch 13/50
23/23 [==============================] - 0s 3ms/step - loss: 959.1223
Epoch 14/50
23/23 [==============================] - 0s 3ms/step - loss: 921.5549
Epoch 15/50
23/23 [==============================] - 0s 2ms/step - loss: 882.4678
Epoch 16/50
23/23 [==============================] - 0s 2ms/step - loss: 846.4235
Epoch 17/50
23/23 [==============================] - 0s 3ms/step - loss: 811.3075
Epoch 18/50
23/23 [==============================] - 0s 2ms/step - loss: 778.0033
Epoch 19/50
23/23 [==============================] - 0s 2ms/step - loss: 746.3566
Epoch 20/50
23/23 [==============================] - 0s 1ms/step - loss: 715.6580
Epoch 21/50
23/23 [==============================] - 0s 4ms/step - loss: 687.2575
Epoch 22/50
23/23 [==============================] - 0s 2ms/step - loss: 659.9419
Epoch 23/50
23/23 [==============================] - 0s 2ms/step - loss: 635.1945
Epoch 24/50
23/23 [==============================] - 0s 2ms/step - loss: 609.9611
Epoch 25/50
23/23 [==============================] - 0s 2ms/step - loss: 588.0090
Epoch 26/50
23/23 [==============================] - 0s 3ms/step - loss: 564.4615
Epoch 27/50
23/23 [==============================] - 0s 2ms/step - loss: 544.1135
Epoch 28/50
23/23 [==============================] - 0s 1ms/step - loss: 524.8364
Epoch 29/50
23/23 [==============================] - 0s 2ms/step - loss: 507.0206
Epoch 30/50
23/23 [==============================] - 0s 1ms/step - loss: 489.7752
Epoch 31/50
23/23 [==============================] - 0s 1ms/step - loss: 474.1080
Epoch 32/50
23/23 [==============================] - 0s 2ms/step - loss: 457.1588
Epoch 33/50
23/23 [==============================] - 0s 1ms/step - loss: 443.5758
Epoch 34/50
23/23 [==============================] - 0s 2ms/step - loss: 429.7380
Epoch 35/50
23/23 [==============================] - 0s 3ms/step - loss: 416.6883
Epoch 36/50
23/23 [==============================] - 0s 3ms/step - loss: 406.1516
Epoch 37/50
23/23 [==============================] - 0s 3ms/step - loss: 394.4934
Epoch 38/50
23/23 [==============================] - 0s 4ms/step - loss: 384.5450
Epoch 39/50
23/23 [==============================] - 0s 3ms/step - loss: 374.2317
Epoch 40/50
23/23 [==============================] - 0s 3ms/step - loss: 363.0587
Epoch 41/50
23/23 [==============================] - 0s 4ms/step - loss: 354.2189
Epoch 42/50
23/23 [==============================] - 0s 3ms/step - loss: 345.8071
Epoch 43/50
23/23 [==============================] - 0s 2ms/step - loss: 337.7536
Epoch 44/50
23/23 [==============================] - 0s 3ms/step - loss: 329.8608
Epoch 45/50
23/23 [==============================] - 0s 1ms/step - loss: 323.2546
Epoch 46/50
23/23 [==============================] - 0s 1ms/step - loss: 315.2220
Epoch 47/50
23/23 [==============================] - 0s 3ms/step - loss: 309.3243
Epoch 48/50
23/23 [==============================] - 0s 1ms/step - loss: 301.9840
Epoch 49/50
23/23 [==============================] - 0s 1ms/step - loss: 295.3226
Epoch 50/50
23/23 [==============================] - 0s 1ms/step - loss: 290.4061

In [18]:
from sklearn.metrics import mean_squared_error
y_pred=model.predict(X_test)
mean_square_error = mean_squared_error(y_test, y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

10/10 [==============================] - 0s 2ms/step
272.5564215976264 0.0

# EVALUATION

In [19]:

total_mean_squared_errors = 50
epochs = 50
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')
print("Below is the mean and standard deviation of " +str(total_mean_squared_errors) + " mean squared errors without normalized data. Total number of epochs for each training is: " +str(epochs) + "\n")
print("Mean: "+str(mean))
print("Standard Deviation: "+str(standard_deviation))

MSE 1: 136.34994506835938
10/10 [==============================] - 0s 1ms/step
MSE 2: 142.10548400878906
10/10 [==============================] - 0s 2ms/step
MSE 3: 115.31888580322266
10/10 [==============================] - 0s 888us/step
MSE 4: 122.90919494628906
10/10 [==============================] - 0s 3ms/step
MSE 5: 125.75450134277344
10/10 [==============================] - 0s 5ms/step
MSE 6: 109.1497802734375
10/10 [==============================] - 0s 0s/step
MSE 7: 130.11756896972656
10/10 [==============================] - 0s 2ms/step
MSE 8: 99.60673522949219
10/10 [==============================] - 0s 561us/step
MSE 9: 137.0558319091797
10/10 [==============================] - 0s 894us/step
MSE 10: 110.39785766601562
10/10 [==============================] - 0s 279us/step
MSE 11: 103.45234680175781
10/10 [==============================] - 0s 882us/step
MSE 12: 108.86429595947266
10/10 [==============================] - 0s 2ms/step
MSE 13: 144.50978088378906
10/10 [==============================] - 0s 2ms/step
MSE 14: 116.52730560302734
10/10 [==============================] - 0s 895us/step
MSE 15: 70.3732681274414
10/10 [==============================] - 0s 2ms/step
MSE 16: 48.70741271972656
10/10 [==============================] - 0s 1ms/step
MSE 17: 53.2803955078125
10/10 [==============================] - 0s 889us/step
MSE 18: 52.140499114990234
10/10 [==============================] - 0s 895us/step
MSE 19: 43.323951721191406
10/10 [==============================] - 0s 2ms/step
MSE 20: 49.18999481201172
10/10 [==============================] - 0s 0s/step
MSE 21: 44.15285110473633
10/10 [==============================] - 0s 1ms/step
MSE 22: 51.78463363647461
10/10 [==============================] - 0s 888us/step
MSE 23: 44.17937469482422
10/10 [==============================] - 0s 3ms/step
MSE 24: 44.12218475341797
10/10 [==============================] - 0s 2ms/step
MSE 25: 48.63007354736328
10/10 [==============================] - 0s 3ms/step
MSE 26: 55.006568908691406
10/10 [==============================] - 0s 4ms/step
MSE 27: 55.350948333740234
10/10 [==============================] - 0s 3ms/step
MSE 28: 50.84782791137695
10/10 [==============================] - 0s 2ms/step
MSE 29: 53.80992126464844
10/10 [==============================] - 0s 2ms/step
MSE 30: 50.749027252197266
10/10 [==============================] - 0s 3ms/step
MSE 31: 50.53030014038086
10/10 [==============================] - 0s 3ms/step
MSE 32: 41.54055404663086
10/10 [==============================] - 0s 3ms/step
MSE 33: 47.0902099609375
10/10 [==============================] - 0s 3ms/step
MSE 34: 46.5020751953125
10/10 [==============================] - 0s 3ms/step
MSE 35: 45.47456359863281
10/10 [==============================] - 0s 3ms/step
MSE 36: 50.44941711425781
10/10 [==============================] - 0s 862us/step
MSE 37: 49.35722351074219
10/10 [==============================] - 0s 887us/step
MSE 38: 52.08047103881836
10/10 [==============================] - 0s 1ms/step
MSE 39: 45.69827651977539
10/10 [==============================] - 0s 2ms/step
MSE 40: 42.819217681884766
10/10 [==============================] - 0s 898us/step
MSE 41: 53.49311828613281
10/10 [==============================] - 0s 0s/step
MSE 42: 44.174041748046875
10/10 [==============================] - 0s 889us/step
MSE 43: 45.46876907348633
10/10 [==============================] - 0s 888us/step
MSE 44: 54.26441192626953
10/10 [==============================] - 0s 278us/step
MSE 45: 50.88966369628906
10/10 [==============================] - 0s 223us/step
MSE 46: 50.664451599121094
10/10 [==============================] - 0s 834us/step
MSE 47: 49.857845306396484
10/10 [==============================] - 0s 914us/step
MSE 48: 48.165283203125
10/10 [==============================] - 0s 2ms/step
MSE 49: 49.480384826660156
10/10 [==============================] - 0s 2ms/step
MSE 50: 50.649085998535156
10/10 [==============================] - 0s 0s/step


Below is the mean and standard deviation of 50 mean squared errors without normalized data. Total number of epochs for each training is: 50

Mean: 69.72834950662823
Standard Deviation: 33.47183043066584